name: Fetch GIS Data and Update Google BigQuery

on:
  schedule:
    - cron: '0 0/24 * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual runs

jobs:
  update_gis_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run GIS Update Script
        env:
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}  # Add PROJECT_ID
          DATASET_ID: ${{ secrets.DATASET_ID }}  # Add DATASET_ID
          GIS_REST_URL: ${{ secrets.GIS_REST_URL }}
        run: python gis_to_bigquery.py
